# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:           pretty

# robots.txt
production:          true

# Setup
url:                 https://burrim.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /recordsblog

title:               records

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         > 
   Blog about random stuff i'm interested in.
  

# The tags listed as entries in the sidebar
sidebar_tags:        [economics, python, random]

# Fallback image and color if not overwritten for tag or post
image:               
color:               '#A85641'

# Fonts
font:                '"Noto Serif", Georgia, serif'
font_heading:        '"Roboto Slab", "Noto Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|Noto+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Burrim'

  # This photo will be used in the about section
  photo:             
  photo2x:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
  

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    # twitter:         _username_
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
     github:          burrim
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_
     rss:              recordsblog/atom.xml

# Remove to disable Google Anaylics
google_analytics_id: 'UA-87747889-5'

# Setting a disqus subdomain will enable the comment section
disqus:              recordsblog

exclude:             [node_modules, package.json]

highlighter: rouge

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
